Added option to configure module to be silent (console.log supression)
Percona-Lab/codeceptjs-saucehelper pull request #5
Opened 2019-04-30 13:51 UTC by AndreKirchner

2019-04-30 14:10 UTC, puneet0191 commented
@AndreKirchner thanks for your contribution, but I think you have not made changes on the latest code, please fetch the latest code from master and send PR, also providing a background for this change would be a great help, please

2019-04-30 14:11 UTC, puneet0191 requested changes

2019-04-30 14:11 UTC, puneet0191 commented on readme.md
> +      "user"   : "SAUCELABS_USERNAME",
We removed it because it can be used from Webdriver Helper config, the same for key

2019-05-02 08:06 UTC, AndreKirchner commented
I can see the issue now. You have not updated the version in package.json with your latest updates - therefore I have been working on an older version. Please update the version number - npm caches might be corrupted due to multiple versions under the same number. Thanks!

2019-05-02 08:06 UTC, closed without merging

2019-05-02 08:27 UTC, AndreKirchner commented
I also think npm registry is not able to determine your changes due to the missing update on the version number -> There will be old versions installed, when using npm i regulary.

2019-05-02 08:36 UTC, puneet0191 commented
@AndreKirchner Fixed, thanks a lot! :+1: